export const siteConfig = {
  name: 'NEXUS DEV PLATFORM',
  description: 'Developer-Powered Technology Company Platform & Marketplace',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  company: {
    name: 'Nexus Engineering Corp',
    tagline: 'BUILD. CREATE. INNOVATE.',
    description: 'Developer-powered technology company building high-performance digital products and systems.',
    leadership: {
      ceo: {
        name: 'Ritesh Lingamallu',
        title: 'CEO / Founder / Admin',
        role: 'CEO',
        bio: 'Leading strategic vision, platform administration, developer verification, and enterprise client relations.',
      },
      md: {
        name: 'M. Shiva Gopi',
        title: 'Managing Director',
        role: 'MD',
        bio: 'Directing technical project oversight, business operations, developer success, and platform monitoring.',
      },
    },
  },
  credits: {
    defaultPriceInInr: 50,
    defaultClaimCost: 1,
    defaultRefundPercentage: 100,
  },
  navItems: [
    { label: 'Home', href: '/' },
    { label: 'Company', href: '/company' },
    { label: 'Projects', href: '/projects' },
    { label: 'Developers', href: '/developers' },
    { label: 'Careers', href: '/careers' },
    { label: 'Contact', href: '/contact' },
  ],
  dashboardNav: [
    { label: 'Overview', href: '/dashboard' },
    { label: 'Profile', href: '/dashboard/profile' },
    { label: 'Projects', href: '/dashboard/projects' },
    { label: 'Messages', href: '/dashboard/messages' },
    { label: 'Community', href: '/dashboard/community' },
    { label: 'Inquiries', href: '/dashboard/inquiries' },
    { label: 'Credits & Wallet', href: '/dashboard/credits' },
    { label: 'Settings', href: '/dashboard/settings' },
  ],
  adminNav: [
    { label: 'Admin Overview', href: '/admin/dashboard' },
    { label: 'Developers', href: '/admin/developers' },
    { label: 'Projects', href: '/admin/projects' },
    { label: 'Clients', href: '/admin/clients' },
    { label: 'Claims', href: '/admin/claims' },
    { label: 'Credits Ledger', href: '/admin/credits' },
    { label: 'Payments', href: '/admin/payments' },
    { label: 'Inquiries', href: '/admin/inquiries' },
    { label: 'Community', href: '/admin/community' },
    { label: 'Support Bridges', href: '/admin/support' },
    { label: 'Analytics', href: '/admin/analytics' },
    { label: 'Platform Settings', href: '/admin/settings' },
  ],
};
