export const LEADERSHIP = {
  CEO: {
    NAME: 'Ritesh Lingamallu',
    ROLE: 'CEO',
    TITLE: 'CEO / Founder / Admin',
  },
  MD: {
    NAME: 'M. Shiva Gopi',
    ROLE: 'MD',
    TITLE: 'Managing Director',
  },
} as const;

export const ROLES = {
  CEO: 'CEO',
  ADMIN: 'ADMIN',
  MD: 'MD',
  DEVELOPER: 'DEVELOPER',
  CLIENT: 'CLIENT',
  SUPPORT: 'SUPPORT',
  GUEST: 'GUEST',
} as const;

export const PROJECT_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  REVIEWING: 'REVIEWING',
  OPEN_FOR_CLAIMS: 'OPEN_FOR_CLAIMS',
  CLAIMS_ACTIVE: 'CLAIMS_ACTIVE',
  SELECTION_PENDING: 'SELECTION_PENDING',
  DEVELOPER_SELECTED: 'DEVELOPER_SELECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED_FOR_REVIEW: 'SUBMITTED_FOR_REVIEW',
  COMPLETED: 'COMPLETED',
  PUBLISHED: 'PUBLISHED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  DISPUTED: 'DISPUTED',
  ON_HOLD: 'ON_HOLD',
} as const;

export const CLAIM_STATUSES = {
  CLAIMED: 'CLAIMED',
  SELECTED: 'SELECTED',
  NOT_SELECTED: 'NOT_SELECTED',
  WITHDRAWN: 'WITHDRAWN',
  DISQUALIFIED: 'DISQUALIFIED',
} as const;

export const CREDIT_TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
  PROJECT_CLAIM: 'PROJECT_CLAIM',
  PROJECT_NOT_SELECTED_REFUND: 'PROJECT_NOT_SELECTED_REFUND',
  PROJECT_CANCEL_REFUND: 'PROJECT_CANCEL_REFUND',
  WITHDRAWAL_REFUND: 'WITHDRAWAL_REFUND',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
  EXPIRATION_REFUND: 'EXPIRATION_REFUND',
} as const;
